apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: gcr.io/categoreyes/categoreyes_client:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: client-config
                  key: REACT_APP_API_BASE_URL
          command: ["/bin/sh"]
          args:
            - -c
            - |
              export REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
              nginx -g 'daemon off;'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  REACT_APP_API_BASE_URL: "http://34.97.70.149:8000"
