apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gcr.io/categoreyes/categoreyes_server:latest
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: SESSION_MIDDLEWARE_KEY
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: SESSION_MIDDLEWARE_KEY
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: server-secrets
                  key: S3_BUCKET
            - name: AWS_DEFAULT_REGION
              value: "ap-northeast-2"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8000
  type: LoadBalancer